service_type: FilterJointTrajectoryWithConstraints
filter_chain:
  -
    name: unnormalize_trajectory
    type: UnNormalizeFilterJointTrajectoryWithConstraints
  -
    name: parabolic_smoother
    type: IterativeParabolicSmootherFilterJointTrajectoryWithConstraints

# Uniformly sample motion (creates smooth motion on controller)
  -
    name: uniform_sample_filter
    type: IndustrialUniformSampleFilterJointTrajectoryWithConstraints
    params: {sample_duration: 0.010}
# Limit the number of points sent to the controller
  -
    name: n_point_filter
    type: IndustrialNPointFilterJointTrajectoryWithConstraints
    params: {n_points: 50}
