// Generated by gencpp from file gripper_driver/force.msg
// DO NOT EDIT!


#ifndef GRIPPER_DRIVER_MESSAGE_FORCE_H
#define GRIPPER_DRIVER_MESSAGE_FORCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_driver
{
template <class ContainerAllocator>
struct force_
{
  typedef force_<ContainerAllocator> Type;

  force_()
    : force1(0.0)
    , force2(0.0)  {
    }
  force_(const ContainerAllocator& _alloc)
    : force1(0.0)
    , force2(0.0)  {
  (void)_alloc;
    }



   typedef float _force1_type;
  _force1_type force1;

   typedef float _force2_type;
  _force2_type force2;




  typedef boost::shared_ptr< ::gripper_driver::force_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_driver::force_<ContainerAllocator> const> ConstPtr;

}; // struct force_

typedef ::gripper_driver::force_<std::allocator<void> > force;

typedef boost::shared_ptr< ::gripper_driver::force > forcePtr;
typedef boost::shared_ptr< ::gripper_driver::force const> forceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_driver::force_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_driver::force_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gripper_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gripper_driver': ['/home/apc16/apc_2016/mario_catkin_workspace/stowing/src/gripper_driver/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gripper_driver::force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_driver::force_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_driver::force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_driver::force_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_driver::force_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_driver::force_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_driver::force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9d3e01eac811d943f8a2b6fd30fe322";
  }

  static const char* value(const ::gripper_driver::force_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9d3e01eac811d94ULL;
  static const uint64_t static_value2 = 0x3f8a2b6fd30fe322ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_driver::force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_driver/force";
  }

  static const char* value(const ::gripper_driver::force_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_driver::force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 force1\n\
float32 force2\n\
";
  }

  static const char* value(const ::gripper_driver::force_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_driver::force_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force1);
      stream.next(m.force2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct force_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_driver::force_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_driver::force_<ContainerAllocator>& v)
  {
    s << indent << "force1: ";
    Printer<float>::stream(s, indent + "  ", v.force1);
    s << indent << "force2: ";
    Printer<float>::stream(s, indent + "  ", v.force2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_DRIVER_MESSAGE_FORCE_H
